/**
 * STARGATE: REMNANTS — Resources
 * Canonical definitions for all 12 resources across 3 tiers.
 * Handles cap calculation, per-tick production, per-day consumption,
 * clamping, and inventory panel rendering.
 */

const Resources = (() => {

  // ── Resource Definitions ─────────────────────────────────────────────────

  /**
   * All resource definitions in tier order.
   * tier 1 = primary (always show in header bar)
   * tier 2 = secondary (show in inventory panel; gathered off-world)
   * tier 3 = tertiary (show in inventory panel; rare/end-game)
   */
  const DEFS = Object.freeze([
    // ── Primary ────────────────────────────────────────────────────────────
    {
      key:         'power',
      label:       'Power',
      glyph:       '⚡',
      tier:         1,
      description: 'Generated by Power Cores. Each installed room consumes 1/day. Blackout halts base operations.',
      producedBy:  ['power_core', 'solar_arrays'],
      consumedBy:  'rooms',
    },
    {
      key:         'food',
      label:       'Food',
      glyph:       '🍖',
      tier:         1,
      description: 'Consumed 1/day per living personnel. Shortage deals hunger damage scaled by Survival stat.',
      producedBy:  ['hydroponics'],
      consumedBy:  'personnel',
    },
    {
      key:         'naquadah',
      label:       'Naquadah',
      glyph:       '◈',
      tier:         1,
      description: 'Primary construction and trade material. Gathered off-world via Survival missions.',
      producedBy:  [],
      consumedBy:  'building, crafting, trade',
    },
    {
      key:         'data',
      label:       'Data',
      glyph:       '💾',
      tier:         1,
      description: 'Generated by Research Lab. Used for research, decoding gate addresses, and Ancient database scans.',
      producedBy:  ['research_lab'],
      consumedBy:  'research, decoding',
    },

    // ── Secondary ──────────────────────────────────────────────────────────
    {
      key:         'artifacts',
      label:       'Artifacts',
      glyph:       '🏺',
      tier:         2,
      description: 'Ancient relics found off-world. Analysing yields decoding hints. Used in some research.',
      producedBy:  [],
      consumedBy:  'research, analysis',
    },
    {
      key:         'alloys',
      label:       'Alloys',
      glyph:       '⚗',
      tier:         2,
      description: 'Refined metals for crafting armour and advanced components.',
      producedBy:  [],
      consumedBy:  'crafting',
    },
    {
      key:         'crystals',
      label:       'Crystals',
      glyph:       '💎',
      tier:         2,
      description: 'Energy-conductive crystals used in gate technology and weapons.',
      producedBy:  [],
      consumedBy:  'crafting, research',
    },
    {
      key:         'medicine',
      label:       'Medicine',
      glyph:       '💊',
      tier:         2,
      description: 'Heals wounded personnel. Required by Med Bay treatments.',
      producedBy:  [],
      consumedBy:  'med_bay, treatment',
    },
    {
      key:         'rarePlants',
      label:       'Rare Plants',
      glyph:       '🌿',
      tier:         2,
      description: 'Exotic flora from off-world biomes. Used in medicine crafting and some research.',
      producedBy:  [],
      consumedBy:  'crafting',
    },

    // ── Tertiary ───────────────────────────────────────────────────────────
    {
      key:         'advancedTech',
      label:       'Adv. Tech',
      glyph:       '🔩',
      tier:         3,
      description: 'Advanced technological components salvaged from off-world labs and crashed vessels.',
      producedBy:  [],
      consumedBy:  'crafting, upgrade',
    },
    {
      key:         'ancientTech',
      label:       'Ancient Tech',
      glyph:       '⌬',
      tier:         3,
      description: 'Technology left behind by the Ancients. Extremely rare. Required for late-game upgrades.',
      producedBy:  [],
      consumedBy:  'research, upgrade',
    },
    {
      key:         'naniteTech',
      label:       'Nanite Tech',
      glyph:       '⊛',
      tier:         3,
      description: 'Replicator-derived nanite components. Highly dangerous but potentially transformative.',
      producedBy:  [],
      consumedBy:  'research, upgrade',
    },
  ]);

  // ── Resource Cap ─────────────────────────────────────────────────────────

  /**
   * Calculate effective storage cap for a given state.
   * Base cap is CONFIG.DEFAULT_RESOURCE_LIMIT (150).
   * A completed Storage room doubles it.
   * @param {GameState} s
   * @returns {number}
   */
  function calcCap(s) {
    const hasStorage = s.rooms.some(r => r.type === 'storage' && !r.constructing);
    return hasStorage
      ? CONFIG.DEFAULT_RESOURCE_LIMIT * 2
      : CONFIG.DEFAULT_RESOURCE_LIMIT;
  }

  // ── Production ───────────────────────────────────────────────────────────

  /**
   * Apply per-TICK resource production from installed rooms.
   * Called every engine tick (1 in-game hour).
   * @param {GameState} s
   * @returns {string[]} log messages for any notable events
   */
  function processTick(s) {
    const cap = s.resourceCap;
    const msgs = [];

    // Power Core: generates power (applied daily, not per-tick — tracked in engine)
    // Hydroponics: +1 food per tick if installed
    if (_hasRoom(s, 'hydroponics')) {
      const before = s.resources.food;
      s.resources.food = Math.min(s.resources.food + 1, cap);
      if (before < cap && s.resources.food === cap) msgs.push('Food storage full.');
    }

    // Advanced Hydroponics (research upgrade): +2 food per tick instead
    if (_hasResearch(s, 'advanced_hydroponics') && _hasRoom(s, 'hydroponics')) {
      // Already got +1 above, add 1 more for the upgrade bonus
      s.resources.food = Math.min(s.resources.food + 1, cap);
    }

    // Research Lab: +1 data per tick
    if (_hasRoom(s, 'research_lab')) {
      s.resources.data = Math.min(s.resources.data + 1, cap);
    }

    // Data Compression research: +1 bonus data per tick
    if (_hasResearch(s, 'data_compression') && _hasRoom(s, 'research_lab')) {
      s.resources.data = Math.min(s.resources.data + 1, cap);
    }

    return msgs;
  }

  /**
   * Apply per-DAY resource consumption (food, power).
   * Called at midnight by the engine.
   * @param {GameState} s
   * @returns {{ foodLog: string, powerLog: string, hungerDeaths: string[] }}
   */
  function processDay(s) {
    const result = { foodLog: '', powerLog: '', hungerDeaths: [] };

    // ── Food consumption ─────────────────────────────────────────────────
    const alive        = s.personnel.filter(p => p.alive);
    const foodNeeded   = _calcFoodNeeded(s, alive);
    const foodAvailable = s.resources.food;

    if (foodAvailable >= foodNeeded) {
      s.resources.food -= foodNeeded;
      result.foodLog = `Food consumed: ${foodNeeded}. Remaining: ${s.resources.food}.`;
    } else {
      s.resources.food = 0;
      const shortage = foodNeeded - foodAvailable;
      // Delegate hunger damage to Personnel module (Survival stat scaling lives there)
      alive.forEach(p => {
        const { died } = Personnel.applyHungerDamage(p, shortage);
        if (died) result.hungerDeaths.push(p.name);
      });
      result.foodLog = `FOOD SHORTAGE — ${shortage} units short. Personnel taking hunger damage!`;
    }

    // ── Power consumption & generation ───────────────────────────────────
    const powerGen  = calcPowerGen(s);
    const powerCost = calcPowerCost(s);
    const powerNet  = powerGen - powerCost;

    s.resources.power = Math.max(0, Math.min(
      s.resources.power + powerNet,
      s.resourceCap
    ));

    const sign = powerNet >= 0 ? '+' : '';
    result.powerLog = `Power: ${sign}${powerNet}/day (gen ${powerGen} − cost ${powerCost}).`;

    // Blackout effect: if power hits 0 and net is negative, log warning
    if (s.resources.power === 0 && powerNet < 0) {
      result.powerLog += ' POWER CRITICAL — base on emergency reserves.';
    }

    return result;
  }

  // ── Power calculations ────────────────────────────────────────────────────

  /**
   * Total power generated per day.
   * @param {GameState} s
   * @returns {number}
   */
  function calcPowerGen(s) {
    let gen = CONFIG.DEFAULT_POWER_GENERATION; // base: 1

    s.rooms.forEach(r => {
      if (r.constructing) return;
      switch (r.type) {
        case 'power_core':
          // Mark II upgrade doubles output
          gen += _hasResearch(s, 'mark_ii_power_core') ? 4 : 2;
          break;
        case 'solar_arrays': // research-unlocked addition
          gen += 1;
          break;
      }
    });

    return gen;
  }

  /**
   * Total power consumed per day (1 per non-default installed room).
   * @param {GameState} s
   * @returns {number}
   */
  function calcPowerCost(s) {
    return s.rooms.filter(r =>
      !r.constructing &&
      r.type !== 'gate_room' &&
      r.type !== 'control_room'
    ).length;
  }

  /**
   * Net power per day (positive = surplus, negative = deficit).
   * @param {GameState} s
   * @returns {number}
   */
  function calcPowerNet(s) {
    return calcPowerGen(s) - calcPowerCost(s);
  }

  // ── Food helpers ─────────────────────────────────────────────────────────

  /**
   * Food needed per day — base 1 per alive personnel;
   * Rationing research halves this (rounded up).
   * @param {GameState} s
   * @param {Personnel[]} alive
   * @returns {number}
   */
  function _calcFoodNeeded(s, alive) {
    const base = alive.length;
    return _hasResearch(s, 'rationing') ? Math.ceil(base / 2) : base;
  }

  // ── Clamp / add ──────────────────────────────────────────────────────────

  /**
   * Safely add an amount to a resource, clamped to [0, cap].
   * @param {GameState} s
   * @param {string} key - resource key
   * @param {number} amount - can be negative
   * @returns {number} actual change applied
   */
  function add(s, key, amount) {
    const before = s.resources[key] ?? 0;
    const after  = Math.max(0, Math.min(before + amount, s.resourceCap));
    s.resources[key] = after;
    return after - before;
  }

  /**
   * Check if the player can afford a cost object.
   * @param {GameState} s
   * @param {{ [key]: number }} cost
   * @returns {boolean}
   */
  function canAfford(s, cost) {
    return Object.entries(cost).every(([key, amt]) =>
      (s.resources[key] ?? 0) >= amt
    );
  }

  /**
   * Deduct a cost object from resources. Returns false if not affordable.
   * @param {GameState} s
   * @param {{ [key]: number }} cost
   * @returns {boolean}
   */
  function spend(s, cost) {
    if (!canAfford(s, cost)) return false;
    Object.entries(cost).forEach(([key, amt]) => {
      s.resources[key] -= amt;
    });
    return true;
  }

  // ── Inventory Panel Rendering ─────────────────────────────────────────────

  /**
   * Render the full inventory panel (all 3 tiers) into #inventory-panel.
   * @param {GameState} s
   */
  function renderInventory(s) {
    const panel = document.getElementById('inventory-panel');
    if (!panel) return;

    const cap = s.resourceCap;
    const r   = s.resources;

    const tiers = [
      { label: 'Primary Resources',   keys: DEFS.filter(d => d.tier === 1) },
      { label: 'Secondary Resources', keys: DEFS.filter(d => d.tier === 2) },
      { label: 'Tertiary Resources',  keys: DEFS.filter(d => d.tier === 3) },
    ];

    panel.innerHTML = tiers.map(tier => `
      <div class="inv-tier">
        <div class="inv-tier-label">${tier.label}</div>
        <div class="inv-grid">
          ${tier.keys.map(def => {
            const val      = r[def.key] ?? 0;
            const pct      = Math.min(100, (val / cap) * 100);
            const isFull   = val >= cap;
            const isEmpty  = val === 0;
            return `
              <div class="inv-card ${isFull ? 'inv-full' : ''} ${isEmpty && def.tier > 1 ? 'inv-empty' : ''}"
                   title="${def.description}">
                <div class="inv-glyph">${def.glyph}</div>
                <div class="inv-label">${def.label}</div>
                <div class="inv-bar-wrap">
                  <div class="inv-bar-fill" style="width:${pct}%"></div>
                </div>
                <div class="inv-amount ${isFull ? 'amber' : ''}">
                  ${val}<span class="inv-cap">/${cap}</span>
                </div>
                ${_renderRateTag(def, s)}
              </div>`;
          }).join('')}
        </div>
      </div>
    `).join('');

    // Power summary block
    const powerSummary = document.getElementById('power-summary');
    if (powerSummary) _renderPowerSummary(s, powerSummary);
  }

  /**
   * Render a small production/consumption rate tag for a resource card.
   */
  function _renderRateTag(def, s) {
    let rate = null;

    if (def.key === 'food') {
      const alive = s.personnel.filter(p => p.alive).length;
      const produced = _hasRoom(s, 'hydroponics') ? (_hasResearch(s, 'advanced_hydroponics') ? 2 : 1) : 0;
      const consumed = _hasResearch(s, 'rationing') ? Math.ceil(alive / 2) : alive;
      const net = produced * 24 - consumed; // per day
      const sign = net >= 0 ? '+' : '';
      rate = { text: `${sign}${net}/day`, positive: net >= 0 };
    } else if (def.key === 'data') {
      const produced = _hasRoom(s, 'research_lab')
        ? (24 + (_hasResearch(s, 'data_compression') ? 24 : 0)) : 0;
      rate = produced > 0 ? { text: `+${produced}/day`, positive: true } : null;
    } else if (def.key === 'power') {
      const net  = calcPowerNet(s);
      const sign = net >= 0 ? '+' : '';
      rate = { text: `${sign}${net}/day`, positive: net >= 0 };
    }

    if (!rate) return '';
    return `<div class="inv-rate ${rate.positive ? 'positive' : 'negative'}">${rate.text}</div>`;
  }

  /**
   * Render the detailed power summary into a container element.
   */
  function _renderPowerSummary(s, el) {
    const gen    = calcPowerGen(s);
    const cost   = calcPowerCost(s);
    const net    = gen - cost;
    const sign   = net >= 0 ? '+' : '';
    const cls    = net >= 0 ? 'positive' : 'negative';

    const roomLines = s.rooms
      .filter(r => !r.constructing && r.type !== 'gate_room' && r.type !== 'control_room')
      .map(r => `<div class="pwr-row dim"><span>${Base.ROOMS[r.type]?.label ?? r.type}</span><span>−1</span></div>`)
      .join('');

    el.innerHTML = `
      <div class="pwr-title">Power Breakdown</div>
      <div class="pwr-row amber"><span>Base generation</span><span>+${CONFIG.DEFAULT_POWER_GENERATION}</span></div>
      ${_hasRoom(s, 'power_core') ? `<div class="pwr-row olive"><span>Power Core${_hasResearch(s, 'mark_ii_power_core') ? ' Mk II' : ''}</span><span>+${_hasResearch(s, 'mark_ii_power_core') ? 4 : 2}</span></div>` : ''}
      ${_hasRoom(s, 'solar_arrays') ? '<div class="pwr-row olive"><span>Solar Arrays</span><span>+1</span></div>' : ''}
      <div class="pwr-divider"></div>
      ${roomLines}
      <div class="pwr-divider"></div>
      <div class="pwr-row pwr-net ${cls}"><span>Net per day</span><span>${sign}${net}</span></div>
    `;
  }

  // ── Internal helpers ─────────────────────────────────────────────────────

  function _hasRoom(s, type) {
    return s.rooms.some(r => r.type === type && !r.constructing);
  }

  function _hasResearch(s, id) {
    return s.research.researched.includes(id);
  }

  // ── Public API ───────────────────────────────────────────────────────────

  /** Return the display label for a resource key, falling back to the key itself. */
  function label(key) {
    return DEFS.find(d => d.key === key)?.label ?? key;
  }

  return {
    DEFS,
    label,
    calcCap,
    calcPowerGen,
    calcPowerCost,
    calcPowerNet,
    processTick,
    processDay,
    add,
    canAfford,
    spend,
    renderInventory,
  };

})();
